### ISSUE TITLE
GitHub faker bundles too slowly on Heroku — lets use rubygems

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#117]

**Comment by jelaniwoods** [comment]
@raghubetina does it make sense to load github faker in development and rubygems faker in production?

**Comment by raghubetina** [comment]
@jelaniwoods I think I would rather have people run into a method missing error in while in development mode, and have to learn about the difference between loading the rubygems version versus the GitHub version if the need something bleeding edge and paying the price for it, than mysteriously have two different gems being loaded invisibly and then failing on production. Thoughts?

**Comment by jelaniwoods** [comment]
> mysteriously have two different gems being loaded invisibly and then failing on production. 

@raghubetina I didn't think about that. Having both version would most likely be _more_ confusing. I agree with your proposal.

**Comment by jelaniwoods** [comment]
Done in https://github.com/appdev-projects/base-rails/blob/09e23e1326c82fc670bc375c026cb4875bdc7772/Gemfile#L17
