### ISSUE TITLE
Add specs to READMEs of projects with summary/details tags

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#122]
Idea: what about adding all specs to the READMEs of projects?

We tell them not to run `rails grade` until they've matched the target, but realistically there's a good argument for running `rails grade` in order to see what all they _really_ have to build since some of the targets include stretch goals.

Instead, we could include specs in the README along with a link to the target; these could be standard inclusions at the top or bottom of every README. In order to keep the specs from becoming too lengthy/overwhelming, [we could use summary/details tags](https://github.blog/2020-04-09-github-protips-tips-tricks-hacks-and-secrets-from-lee-reilly/#the-devils-in-the-details).

It might be possible to write an automated script that would generate this markdown from the contents of the spec folder.

**Comment by raghubetina** [comment]
Bumping this idea. @jelaniwoods @pmckernin do you agree/disagree?

I think we should start including the specs in every README; it could be the output of rspec in documentation format when run against the target (e.g. all tests passing).

It seems fair that they should have specs in hand, in addition to the target, in order to know what to _do_; and we should still encourage them strongly to _test manually_ before running the automated tests.

@jelaniwoods If you agree can you update this week's HTML assignments' READMEs with specs? Hopefully that will cut down on some of the questions we got, in addition to the other updates you made to the specs themselves.

**Comment by jelaniwoods** [comment]
@pmckernin and @raghubetina if you're interested I wrote a script that does this https://github.com/jelaniwoods/dotfiles/blob/master/specs_to_readme.rb

**Comment by raghubetina** [comment]
@jelaniwoods Yay! 👏🏾
