### ISSUE TITLE
Ferrum doesn't seem to work on a fresh appdev_template app

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#128]
Ferrum still doesn't seem to work on a fresh appdev_template app:

https://github.com/appdev-projects/coming-soon/pull/1

**Comment by jelaniwoods** [comment]
@raghubetina The example that I used before still seems to work in a newly generated repo

My first test was here https://github.com/firstdraft/appdev/issues/223#issuecomment-594837037

I copied coming-soon to the coming-soon repo [here](https://github.com/jelaniwoods-FurtherLearning/test-coming-soon) so I could open it in Gitpod, add `ferrum`, and run the test task which still seems to work. Here's a snapshot
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/58438ce4-6ef5-4099-b23a-a3a5d75fd90d)

**Comment by jelaniwoods** [comment]
Closing this, since it's been resolved.
