### ISSUE TITLE
Proposal: replace activeadmin with rails_db

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#141]
Proposal: replace [activeadmin](https://activeadmin.info/) with [rails_db](https://github.com/igorkasyanchuk/rails_db).

Rationale:

The purpose of including ActiveAdmin in appdev projects was so that students can get a quick visual view of database tables. `rails_db` provides that in a more direct way.

 - Doesn't require the additional step of signing in.
 - Doesn't confuse the issue of needing to implement user roles themselves.
 - Doesn't clutter `routes.rb`.
 - Doesn't clutter the models folder with  `AdminUser` and `AdminComment`, or require the hack of moving elsewhere and adding to the load path.
 - Doesn't need the `app/admin` folder with files that look confusingly similar to models.
 - Can teach the students to use `rails g model` instead of `rails g draft:model`; I believe the only extra work that the latter does is register the model with activeadmin. This results in extra visual output that I have to handwave away when I am introducing models.

Thoughts @jelaniwoods @pmckernin ? 

![Screen Shot 2020-05-17 at 5.17.14 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/49e14cc5-ef69-4d8c-aae3-c4814150db17/Screen+Shot+2020-05-17+at+5.17.14+PM.png)

**Comment by pmckernin** [comment]
I would agree that this would be a good change.  Out of my time as a TA I can only recall only one instance of a student referring to using ActiveAdmin.

**Comment by jelaniwoods** [comment]
Oh this looks nice! I always thought the main reason for `draft:model` was to stay consistent with any other generator they would use. I don't know if the distinction would be confusing or not.

**Comment by raghubetina** [comment]
@jelaniwoods I could get behind renaming the other two (`draft:resource` => `resource`, `draft:layout` => `layout`).
