### ISSUE TITLE
rails new --minimal or some variant?

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#151]
Should we use this or some variant of it?

https://github.com/rails/rails/pull/39282

**Comment by JeffCohen** [comment]
YES.  I think minimal straight up is probably perfect (unless you have first draft-specific gems that you also like).

I also wish `rails new` implied `--minimal` by default :-)

**Comment by raghubetina** [comment]
@JeffCohen Yes there are a few different gems we'd add in on top; `web_git`, etc.

I would like one master gem, `appdev` or something, that pulls in all the other gems that we like to add. Do you have any advice on how that should be structured, @JeffCohen, or an example that we should look at for inspiration? Is that what railties is?

**Comment by JeffCohen** [comment]
Hey great question.  

I think the best reference is the `rails` gem itself.  Although the rails repository contains all the code, the rails gem itself is only one file, a README.md file.  The rest gets pulled in from the dependency list.  

Here's the code, the dependencies start on line 31: https://github.com/rails/rails/blob/master/rails.gemspec#L31

(IIRC the `railties` gem is sort of the "bottom" of the stack, providing a lot of bootstrapping/code-loading code, and doesn't really have any dependencies of its own).

**Comment by raghubetina** [comment]
@JeffCohen Perfect, thank you as always sir.

**Comment by jelaniwoods** [comment]
Resolved in https://github.com/firstdraft/appdev_template/pull/157
