### ISSUE TITLE
Include Heroku changes

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#16]
- in Gemfile, gem pg and rails_12factor in production group, switch sqlite3 to development
 - devise secret key
 - Procfile

```
web: bundle exec puma -p $PORT -C ./config/puma.rb
release: bundle exec rails db:migrate
```

**Comment by jelaniwoods** [comment]
Procfile was added in https://github.com/firstdraft/appdev_template/commit/74e9d8121718f2aef89dd36836573621480f7269

We no longer use devise and the mentioned gems are outdated as of Rails 6.
