### ISSUE TITLE
Heroku Removing Gemfile.lock because it was generated on Windows

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#160]
I notice Heroku "Removing Gemfile.lock because it was generated on Windows". This caused an issue with the Google Translate gem; it stopped working after using a different version in production.

StackOverflow says:

https://stackoverflow.com/questions/20297205/heroku-removing-gemfile-lock-because-it-was-generated-on-windows

Since we and the students are all *nix, perhaps we can safely have `appdev_template` remove `remove `x86-mingw32`? Thoughts?

**Comment by jelaniwoods** [comment]
I think it makes sense to remove it then. I assume it has to do with 
```ruby
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
...
`bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`
```

There are a few other options listed here https://github.com/tzinfo/tzinfo-data/issues/12#issuecomment-279554001 are there any preferences on how to resolve?
