### ISSUE TITLE
ActionView dependency bundling errors

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#168]
Right now when I create a new app with the template, I get a series of dependency issues when `bundle`ing:

```
Bundler could not find compatible versions for gem "actionview":
  In snapshot (Gemfile.lock):
    actionview (= 6.0.3)

  In Gemfile:
    dotenv-rails was resolved to 2.7.5, which depends on
      railties (>= 3.2, < 6.1) was resolved to 6.0.3, which depends on
        actionpack (= 6.0.3) was resolved to 6.0.3, which depends on
          actionview (= 6.0.3)

    rails (~> 6.0.3, >= 6.0.3.2) was resolved to 6.0.3.2, which depends on
      actionview (= 6.0.3.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

I think this is because, in the Gemfile, there is:

```ruby
gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
```

Why the two different version directives? Perhaps it should only have `'~> 6.0.3'`?

**Comment by jelaniwoods** [comment]
@raghubetina I'm not able to reproduce this error. When I generate a new application it bundles without issue.

As for the `rails` version directives, this was also the case for [photogram-final](https://github.com/appdev-projects/photogram-final/blob/8de1deee34414fb88fb39c56fdd4b15857e61d22/Gemfile#L7)

This also appears to happen when I just do a regular `rails new`.
