### ISSUE TITLE
Rename `bin/server` to `bin/dev`

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#179]
Since Rails 7 now has a `bin/server`-esque thing out of the box, let's rename ours to match the new framework convention — `bin/dev`. Less typing, as well.

Let's wait until after Spring quarter ends to do this, since we've already started them on `bin/server`. (Or, if we're ready to switch projects to Rails 7 for summer quarter, then we need to modify the generated `bin/dev` with our enhancements.)

**Comment by jelaniwoods** [comment]
Completed in https://github.com/appdev-projects/rails-7-template/pull/2
