### ISSUE TITLE
Make it work again

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#29]
The template seems to have gotten rusty and no longer works due to e.g. updates to rspec and Ruby.

Make it work again.

**Comment by jelaniwoods** [comment]
Some specifics:
- Specific sqlite3 version
- There is an error generating the `rails_helper.rb` for Rspec

**Comment by jelaniwoods** [comment]
I'm experiencing an issue running this with Ruby version 2.6.0. Any gem install command, `rails g annotate:install`, `rails g rspec:install`, active admin, etc, inexplicitly hang when run.  The same template file seems to work with Ruby 2.5.3.
