### ISSUE TITLE
Add a dummy spec to new projects

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#41]
Add this to new projects:

```ruby
# specs/features/dummy_spec.rb

require "rails_helper"

describe "This project" do
  it "is not graded" do
    expect(1).to eq(1)
  end
end
```

In order to prevent the error in grade_runner when there are no specs.

**Comment by jelaniwoods** [comment]
@raghubetina I assume this does not include the final project?

**Comment by raghubetina** [comment]
@jelaniwoods Maybe change the copy — `it"is up to you to write specs for your project, if you want to!" do`

**Comment by jelaniwoods** [comment]
@raghubetina Okay, got it.
