### ISSUE TITLE
Remove Ruby version from Gemfile.lock

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#49]
Currently when I create an app using the template, a Ruby version winds up in the `Gemfile.lock`. For example, `bootstrap-intro` has `2.3.4`.

If possible I would like to avoid this, to maintain the widest possible compatibility. For example, having `2.3.4` in that file means that Cloud9 can run the code, but Heroku cannot. Any other version in there will mean Cloud9 cannot.

When and why does that number end up in `Gemfile.lock`? Can we prevent it? Is there any harm in deleting it?

**Comment by jelaniwoods** [comment]
It *seems* like you have to manually delete the `RUBY VERSION` from the `Gemfile.lock` at least judging from [this answer](https://stackoverflow.com/questions/36316399/can-i-stop-bundler-from-adding-ruby-version-to-gemfile-lock)

You can delete it, but it will always be put back in when you `bundle`.

**Comment by jelaniwoods** [comment]
@raghubetina There doesn't seem to be a good solution to this from what I can find. What are your thoughts?

**Comment by raghubetina** [comment]
@jelaniwoods Let's proceed under the assumption that we're going to be using repl.it (since it looks like progress on that front is looking good) and therefore we'll control the environment completely; so let's find out what version of Ruby repl.it's Rails machines use and then use that version in `appdev_template`. How does that sound?

**Comment by raghubetina** [comment]
Or, I guess there's not really anything to be done in `appdev_template`, come to think of it; we just have to remember to set the correct Ruby version when we do the `rails new`?

**Comment by jelaniwoods** [comment]
@raghubetina  Yeah I think it makes more sense to set the version with `rails new`.
