### ISSUE TITLE
Add spinners for dev:prime task

### ISSUE THREAD

**Issue by jelaniwoods** [firstdraft/appdev_template#55]
Use this [gem](https://github.com/piotrmurach/tty-spinner)

**Comment by jelaniwoods** [comment]
![rails_dev_prime_spinners](https://user-images.githubusercontent.com/17581658/61414864-b4a80280-a8b4-11e9-90c9-b123f97079e7.gif)

**Comment by jelaniwoods** [comment]
@raghubetina I think something like this could be nice, especially when the `dev:prime` takes a while to run. What do you think?

**Comment by raghubetina** [comment]
@jelaniwoods Love it! Nice work 🙌🏾
