### ISSUE TITLE
Add .codio

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#57]
I'm not sure yet how to make this global in Codio, but for now let's add this `.codio` file to our repos to get the correct menu bar items:

```
{
// Configure your Run and Preview buttons here.

// Run button configuration
  "commands": {
        "Initial project setup (bin/setup)": "bin/setup",
        "Start web server (rails server)": "rails server -b 0.0.0.0",
        "Run database migrations (rails db:migrate)": "rails db:migrate",
        "Hydrate with dummy data (rails dev:prime)": "rails dev:prime"
  },

// Preview button configuration
  "preview": {
        "Live app": "http://{{domain3000}}/",
        "Git client": "http://{{domain3000}}/git",
        "ActiveAdmin": "http://{{domain3000}}/admin",
        "Current File (static)": "http://{{domain}}/{{filepath}}"     
  }
}
```

**Comment by jelaniwoods** [comment]
@raghubetina Did you want the command to be `rails dev:prime`? or `rails dummy`? I'm updating the template now and had started to replace `dev:prime` with `dummy`.

**Comment by raghubetina** [comment]
@jelaniwoods I'm re-re-re-re-thinking it now and leaning towards sticking with `dev:prime`, due to the ability to add the buttons to the menu bar for `db:migrate`, `db:seed`, and `dev:prime`. Also because I already showed the `draft:model` yesterday 😔

**Comment by raghubetina** [comment]
But we can rename or alias `draft:model`, and avoid using namespaces for anything that they have to type.

**Comment by jelaniwoods** [comment]
@raghubetina  Okay! I'll make sure the template uses `rails dev:prime` for now then. I'll also update msm-queries and photogram-queries to have `dev:prime` instead of `dummy`.

**Comment by raghubetina** [comment]
@jelaniwoods I updated the above with links for Git Client and Active Admin. This means we can remove `dev_toolbar` from the checklist and appdev_template.
