### ISSUE TITLE
Add views/application folder in appdev_template

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#59]
I would like new rails apps to start with a `views/application` folder.

**Comment by jelaniwoods** [comment]
@raghubetina usually view folder names follow the convention of `_template`. Should this `application` folder be an exception to this rule?

**Comment by raghubetina** [comment]
@jelaniwoods Excellent observation; but yes, in this case I'd like to make an exception. The goal is to be able to get "Hello, world!" to show up as simply as humanly possible the very first time they make a route. With this folder in place, all we will need to do is: 

```ruby
match("/rock", { :controller => "application", :action => "play_rock", :via => "get" })
```

No need to create controller

```ruby
def play_rock
  render("hi.html.erb")
end
```

Add view template

What do you think?

**Comment by jelaniwoods** [comment]
@raghubetina I do like the having this as an exception and it being easy to do a hello world webpage. I think we have to be explicit in our explanation; using the render method in the application controller will look in the application views folder.
