### ISSUE TITLE
Eliminate all traces of `circle.yml`

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#63]
I still see circle.yml [appearing in projects](https://github.com/appdev-projects/photogram-queries/blob/master/circle.yml) from time to time. Let's eliminate all traces of it in the template/checklist.

**Comment by jelaniwoods** [comment]
Fixed in [this commit](https://github.com/firstdraft/teachersmanual/commit/54cd652b34db8c312ae25af4ebda2786d0081653) I named the commit incorrectly since I thought this issue was a part of the same repository but it's not.
