### ISSUE TITLE
Initialize `ActiveRecord::Base.include_root_in_json = true`

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#73]
I'd like to switch to teaching `as_json` rather than `to_json`, and let's initialize the default for `ActiveRecord::Base.include_root_in_json` to `true`.

What's the best place for this? I'm not sure, maybe do some research to see where others are doing it; off the cuff, perhaps an initializer called `active_record/base.rb`? Or maybe just in `application.rb`?

**Comment by jelaniwoods** [comment]
It looks like the `wrap_parameters.rb` initializer is [the place for this configuration](https://stackoverflow.com/a/12523100) but is commented out by default. I'll look more into it.
