### ISSUE TITLE
Can we remove the diff2html install step from bin/setup?

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#8]
Since students use only one workspace now, it's a waste of time to re-install diff2html with every `bin/setup`.

Maybe we should test for the presence of the WebGit gem, and then if detected, check the system for diff2html, and then only if it is not present — then install it?

**Comment by jelaniwoods** [comment]
Resolved in https://github.com/firstdraft/appdev_template/commit/4988f974e6e03959f993c1a3b2b39a532411a077
