### ISSUE TITLE
Copy for AR:Relation patch

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#96]
What do you think of changing the copy in `active_record_relation_patch.rb` from:

```
"Array containing #{row_count} #{model} #{"record".pluralize(row_count)}"
```

to

```
"#{self.class} (array with #{row_count} #{model} instances inside)"
```

This will be part of our larger project to refer to relations as relations rather than collections, etc, and encourage frequent use of `.class` .

(I purposely removed the smart pluralization because I want them to see the dissonance of "1 records inside".)

**Comment by jelaniwoods** [comment]
FIxed in #95
