### ISSUE TITLE
Audit Heroku pre-configuration

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#97]
Read through Heroku's Puma guide and make sure that appdev_template's `puma.rb` configuration, and generally Heroku configuration, is up to date for Rails 6.

https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server

If there are any changes, please also update our [new app checklist](https://trello.com/b/TmHFpMyb/checklist-new-rails-app).

**Comment by jelaniwoods** [comment]
@raghubetina the new app checklist says to add rack timeout, should that also be added to the template?

**Comment by raghubetina** [comment]
@jelaniwoods Hm. If so then we should increase the timeout to the Heroku max of 30 seconds, for students. The default of 15 is a good number for our own apps.

https://devcenter.heroku.com/articles/request-timeout

**Comment by raghubetina** [comment]
@jelaniwoods Does Heroku still recommend adding that gem in their guide?

**Comment by jelaniwoods** [comment]
@raghubetina Yes, the guide still suggests to add the Rack Timeout gem.

**Comment by raghubetina** [comment]
@jelaniwoods Okay, let's do in in appdev_template then, but let's increase the timeout to 30.
